variables:
  RAILS_ENV: test

before_script:
  - bundle config build.nokogiri --use-system-libraries
  - bundle install --path=/home/gitlab-runner/builds/shared/${CI_PROJECT_NAME}/gems
  - cp config/secrets.yml.example config/secrets.yml
  - cp config/database.yml.example config/database.yml

test:
  script:
    - bundle exec rake

deploy:
  only:
    - master
  script:
    - bundle exec cap production_1 deploy
    - bundle exec cap production_2 deploy
